### ISSUE TITLE
Notification of Wrong Password Can be Improved

### ISSUE THREAD

**Issue by ChihweiLHBird** [datajoint/datajoint-labbook#119] opened 2021-03-06 00:46 UTC
I think it is better to have `password or username incorrect` instead of the current notification `name 'get_host_hook' is not defined`

![image](https://user-images.githubusercontent.com/43905414/110188880-81dcb600-7dda-11eb-9b7b-8048180b2ebe.png)

**Comment by Synicix** [comment] 2021-03-06 03:23
That is odd, we do have an error message for incorrect password and username entry. That error code is something different it seems.

![image](https://user-images.githubusercontent.com/10690095/110193336-f9214280-7df8-11eb-9d88-4c5a850cd9cb.png)

**Comment by ChihweiLHBird** [comment] 2021-03-06 05:03
> That is odd, we do have an error message for incorrect password and username entry. That error code is something different it seems.
> 
> ![image](https://user-images.githubusercontent.com/10690095/110193336-f9214280-7df8-11eb-9d88-4c5a850cd9cb.png)
> 
> Are you able to create a fake crediential for that server so we can check out where this error is coming from?

Maybe the reason is that our server's version is outdated, let me check that.

**Comment by Synicix** [comment] 2021-03-06 05:15
If you could figure how to replicate it that would be great. Otherwise there isn't much for me to work off yet. Thanks for looking into this.

**Comment by rgerkin** [comment] 2021-03-08 16:54
@Synicix How do we find out our server version (this is a djneuro hosted instance)?

**Comment by guzman-raphael** [comment] 2021-03-08 17:00
@ChihweiLHBird Thanks for the report and @Synicix thanks for looking into this.

Upon review it appears this issue is specifically unique to DataJoint NEURO hosted users. To reproduce it, you would need to connect with a DataJoint NEURO hosted instance and type the wrong password.

For this case, the error handling is simply just displaying the error perceived by the `pharus` backend. However, the error is being truncated since there are multiple exceptions on the stack thrown by DataJoint Python itself. I believe the appropriate fix for this is to improve the error handling on DataJoint Python for this case so that it propagates properly through the `pharus` backend and to the `datajoint-labbook` frontned.

@ChihweiLHBird @rgerkin Checking the server version here seems unrelated by in any case you would do this with `dj.conn().query('SELECT @@VERSION;').fetchall()`.

**Comment by rgerkin** [comment] 2021-03-08 17:05
@guzman-raphael OK, so if the password is wrong (and this will go away if we enter it correctly) can you provide me (or @ChihweiLHBird) with the correct password via the support ticket system or email?  I believe @ChihweiLHBird has been successfully using this password for insertion/deletion tests previously, so I'm not sure what happened.

**Comment by guzman-raphael** [comment] 2021-03-08 19:19
@rgerkin I think a password reset is in order for @ChihweiLHBird in your DataJoint NEURO Hosted instance (the one in the screenshots above). We'll follow up separately on the support ticket you created in https://support.djneuro.io/portal/en/home to resolve this.

@ChihweiLHBird In the meantime, feel free to use the tutorial database with your DataJoint credentials. That should work plus it will include the sample schema I created and shared with you for development/testing.

```
Host/Database Address: tutorial-db.datajoint.io
Username: zliang27
Password: <your_password>
```

**Comment by rgerkin** [comment] 2021-03-08 19:43
@guzman-raphael Should he use literal `<your_password>` for the tutorial database, or the new password you are going to reset for him (which could also be used for our hosted instance?)

**Comment by rgerkin** [comment] 2021-03-08 19:51
@guzman-raphael Disregard, I am following up with Chris on Slack for clarification.

**Comment by ChihweiLHBird** [comment] 2021-03-08 23:46
> @rgerkin I think a password reset is in order for @ChihweiLHBird in your DataJoint NEURO Hosted instance (the one in the screenshots above). We'll follow up separately on the support ticket you created in https://support.djneuro.io/portal/en/home to resolve this.
> 
> @ChihweiLHBird In the meantime, feel free to use the tutorial database with your DataJoint credentials. That should work plus it will include the sample schema I created and shared with you for development/testing.
> 
> ```
> Host/Database Address: tutorial-db.datajoint.io
> Username: zliang27
> Password: <your_password>
> ```

Thank you!

**Comment by guzman-raphael** [comment] 2021-03-12 19:20
@ChihweiLHBird Closing as we've filed a more appropriate issue (datajoint/datajoint-python#879) to properly address this. Let us know if you encounter any further problems.

**Closed by guzman-raphael** 2021-03-12 19:20 UTC
Labels: bug
