### ISSUE TITLE
get_host_hook / plugin in Docker container

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-labbook#153] opened 2021-06-03 16:03 UTC
### Description

Via paid support Nº 148:

```
P.S. It still says "name 'get_host_hook' is not defined" when I
use the wrong password, instead of a more sane error message
related to the password being wrong.  I see that you have an
issue indicated that you fixed it

(https://github.com/datajoint/datajoint-python/issues/879)

but it apparently did not make it into the Dockerfile you are
using for LabBook.  What version is the first to include that
fix, and will you be updating the Dockerfile for LabBook
accordingly?
```

**Comment by guzman-raphael** [comment] 2021-06-07 23:16
Closing this as a duplicate of #119.

**Closed by guzman-raphael** 2021-06-07 23:16 UTC
Labels: bug
